### ISSUE TITLE
[Bug]: sometimes styles are not applied to .is-next-container

### ISSUE THREAD

**Issue by ScoobyDid** [swup/parallel-plugin#13] opened 2024-01-24 17:31 UTC
### What did you expect? 🧐

Styles to apply to .is-next-container before class is removed

### What actually happened? 😵‍💫

Styles are not applyed to .is-next-container before class is removed.

This issue only occurs when plugin is included from a CDN as UMD module (as it is suggested in [documentation](https://swup.js.org/plugins/parallel-plugin/#installation)). It took me a while to figure out that forceReflow function is not included in [output file](https://unpkg.com/@swup/parallel-plugin@0.3.0/dist/index.umd.js) - class is applied and then immediately removed:

![Screenshot 2024-01-24 211447](https://github.com/swup/parallel-plugin/assets/66004223/69fff7dc-5d71-4064-896a-9366a9cba5b8)

Although it is included in [module file](https://unpkg.com/@swup/parallel-plugin@0.0.2?module), that's why it works correctly in  [your demo](https://replit.com/@swupjs/Swup-Demo-Reveal) (it uses CDN link with module), but have inconsistent behavior in [this demo](https://stackblitz.com/edit/web-platform-bmtpwk?file=index.html,page-2.html,page-3.html,page-4.html,base.css,pages.css,transitions.css,swup.js) (same code, but uses CDN UMD link)

### Swup and plugin versions 📝

- swup: 4.5.1
- parallel-plugin: 0.3.0

### What browsers are you seeing the problem on? 🧭

Firefox, Chrome, Safari, Microsoft Edge

### URL to minimal reproduction 🔗

https://stackblitz.com/edit/web-platform-bmtpwk?file=index.html,page-2.html,page-3.html,page-4.html,base.css,pages.css,transitions.css,swup.js

### Checked all these? 📚

- [X] I have read and searched the [official docs](https://swup.js.org)
- [X] I have checked [discussions](https://github.com/orgs/swup/discussions) and [existing issues](https://github.com/issues?q=is:issue+org:swup) for related problems
- [X] I agree to follow this project's [Code of Conduct](https://github.com/swup/.github/blob/master/CODE_OF_CONDUCT.md)
- [X] I have provided all necessary information to the best of my knowledge

**Comment by daun** [comment] 2024-01-24 19:24
Thanks for investigating! This looks to be a minification issue — the `forceReflow` helper just reads the `offsetHeight` of the body if I remember correctly and Terser seems to discard any methods that just read and don't modify anything. We'll need to see if this can be configured or if we find a different workaround.

**Comment by daun** [comment] 2024-01-24 19:34
There seems to be [a magic comment](https://github.com/developit/microbundle/blob/4b11285f27e7fa5a5f9ff4733489bb75e8a0763d/test/fixtures/terser-annotations/src/index.js#L11C20-L11C37) to disable inlining of functions in microbundle. I'll see if that solves the issue.

```js
export default function main(a, b) {
  const inlined = /*@__INLINE__*/ shouldBeInlined(a, b);
  const preserved = /*@__NOINLINE__*/ shouldBePreserved(a, b);
  return { inlined, preserved };
}
```

**Comment by ScoobyDid** [comment] 2024-01-24 19:59
If this won't work properly, i think removing class within requestAnimationFrame should work just fine;

**Comment by hirasso** [comment] 2024-01-24 20:15
You mean enable, right?

**Comment by daun** [comment] 2024-01-24 22:02
@ScoobyDid Returning `true` should do the trick. We had started with requestAnimationFrame for the plugin, but after lots of trial and error it turned out that a forced reflow was required to get perfectly synchronous enter and leave animations.

@hirasso Now I'm confused 🤠 I assume we'd want to disable inlining to increase the chance of the function being kept in the output. But returning `true` should be the better solution here anyway.

**Comment by hirasso** [comment] 2024-01-24 22:32
@daun oops no, I got it backwards 😅 please ignore my comment 🫠

**Comment by daun** [comment] 2024-01-26 17:04
Created a PR with a working fix on the core repo: [#868](https://github.com/swup/swup/pull/868)

**Comment by daun** [comment] 2024-01-27 11:11
This is fixed in the latest releases of swup and this plugin. Feel free to reopen if you're still seeing the issue, but I've confirmed the reflow helper is kept during minification. Thanks for reporting and investigating @ScoobyDid!

**Closed as completed by daun** 2024-01-27 11:11 UTC

**Comment by ScoobyDid** [comment] 2024-01-27 13:33
Awesome! Thanks for fixing it; tested it in this [demo](https://stackblitz.com/edit/web-platform-bmtpwk?file=index.html,page-2.html,page-3.html,page-4.html,base.css,pages.css,transitions.css,swup.js) and now it works as expected!
